version: "2"
sql:
  - engine: "postgresql"
    queries: "internal/infrastructure/task/sql/queries.sql"
    schema: "internal/infrastructure/task/sql/schema.sql"
    gen:
      go:
        package: "sqlc"
        out: "internal/infrastructure/task/sqlc"
        sql_package: "pgx/v5"
        emit_json_tags: true
        emit_prepared_queries: false
        emit_interface: false
        emit_exact_table_names: false
        emit_empty_slices: true

